---
version: 2.0
targets:
  copy-network-device-plugin-artifacts:
    commands: ["sh", "-c", "cd /k8s-network-device-plugin && /device-plugin-asset-push.sh"]
    owners: ["email:Shiv.Tyagi@amd.com"]
    area:
    sub-area:
    feature:
    build-dependencies:
      - build-network-device-plugin
      - build-network-device-plugin-docker
      - build-network-device-plugin-helm-chart

image:
  bind_dir: /go/src/github.com/ROCm/k8s-network-device-plugin
  work_dir: /go/src/github.com/ROCm/k8s-network-device-plugin
